services:
  mongodb:
    image: mongo:latest
    container_name: my-tasks-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-tasks-network

    
volumes:
  mongodb_data:

networks:
  my-tasks-network:
    driver: bridge